sonar.projectKey=ArchLens-Fiap_archlens-gateway
sonar.organization=archlens-fiap
sonar.projectName=archlens-gateway
sonar.sources=src/
sonar.tests=tests/
sonar.exclusions=**/bin/**,**/obj/**,**/*.Designer.cs
sonar.cs.opencover.reportsPaths=coverage/**/coverage.opencover.xml
sonar.coverage.exclusions=**/Program.cs,**/Migrations/**
